name: 03 - Workflow Runners
on: push
jobs:
    ubuntu-echo:
        runs-on: self-hosted
        steps:
            - name: Show OS
              run: |
                echo "This job is running on a self-hosted runner"
                echo "Runner OS: $RUNNER_OS"